version: '3.5'
services:
    mysql:
        restart: always
        image: mysql:5.7
        container_name: luna_activity
        ports:
            - 3306:3306
        environment:
            TZ: Asia/Shanghai
            MYSQL_ROOT_PASSWORD: foobar
            MYSQL_USER: foobar
            MYSQL_PASSWORD: foobar
        command:
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_general_ci
            --explicit_defaults_for_timestamp=true
            --lower_case_table_names=1
            --max_allowed_packet=128M
            --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
        volumes:
            - "./data/db:/var/lib/mysql"
            - "./conf/my.cnf:/etc/my.cnf"
            - "./sql:/docker-entrypoint-initdb.d/"  # 项目启动时自动执行 ./sql 目录下的sql文件


